### ISSUE TITLE
Use case diagrams for meeting with Katrin on Nov 5th

### ISSUE THREAD

**Issue by acferreir4** [acferreir4/UNESCO-Database-Project#10]
We discussed making use case diagrams, illustrating how the website will function etc.

We should have this finished by Sunday Nov 4th. I'd like to send her what we come up with so that she can adequately prepare for our meeting.

Assigned to Shahriar since he made the most progress, but should be a group effort.

**Comment by DhruboCSE** [comment]
First demo completed

[Demo.pdf](https://github.com/acferreir4/UNESCO-Database-Project/files/2546104/Demo.pdf)
