### ISSUE TITLE
Compile a list of questions for our next meeting with stakeholders

### ISSUE THREAD

**Issue by acferreir4** [acferreir4/UNESCO-Database-Project#3]

**Comment by Dhruboeecs** [comment]
Add the following questions 
- What are all the type of data that we need to handle in this project (excel, text from doc/txt file etc, power points)? Please list the type of docs.
- Please provide all type of file structure that we need to work on with it's structure. For example for

File Type 1:
Includes: **18_07_15_Country List.xlsx**, **18_07_16_Country_Asia.csv**, **18_07_17_NA List.xyz**  
```
1. Region
2. Country
3. Research Institution
4. City
5. Met
6. MoC
7. Status request
8. RI 1 tools
9. general
10. Role
11. Contact Person(s)
12. Function <<of Contact Person(s)>>
13. Contact	Contact Person(s) II
14. Function <<of Contact Person(s) II>>
```
- Please provide all the relation that each file has with each other. For example if there is any relationship between. If you have two tables lets say A and B. Please let us know if A's column has any relation with B's colum values. same for rows.
