### ISSUE TITLE
Set up a working prototype using our proposed techonologies

### ISSUE THREAD

**Issue by acferreir4** [acferreir4/UNESCO-Database-Project#8]
Can we make a prototype to base our work on? Using the things we discussed like:
 - Flask / Django
 - MySQL / PostgreSQL
 - Front-end Framework (AngularJS or w.e)

Basically set up an input field on a web page and see if we can store in db.
I'll close the issue once we have it working.

**Comment by DNSheng** [comment]
A flask prototype was submitted under a new ds-flask-prototype branch. 7f8d88e080f19610186ba3483ff7363ed63bfdaa
